version: '3.5'

# basic user setup, used for extending users easily
# source: https://medium.com/@kinghuang/a1e4105d70bd
x-user: &user-template
  image: andreasmalling/ft_user
  build: ./user
  volumes:
    - ./video_dashed/:/usr/src/app/video_dashed/
  depends_on:
    - bootstrap
    - metric
    - network
    - host

services:
  # user for debugging, with sound and display pass-through
  user_debug:
    <<: *user-template
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:- :0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/snd:/dev/snd
    command: ${USER_DEBUG:- -r 0 --head BINGE}

  # user which adds content from videos_dashed to local IPFS network
  user_seed:
    <<: *user-template
    command: ${USER_SEED:- -r 0 SEEDER}
  
  # users for persona clients
  user_1:
    <<: *user-template
    command: ${USER_1:- IDLE}

  user_2:
    <<: *user-template
    command: ${USER_2:- IDLE}

  user_3:
    <<: *user-template
    command: ${USER_3:- IDLE}

  # Main network: 
  # =============
  # IPFS node used for bootstraping local network
  bootstrap:
    image: andreasmalling/ft_bootstrap

  # python server hosting the website for the web player
  host:
    image: andreasmalling/ft_host
    build: ./website
    volumes:
      - ./website:/usr/src/app/

  # client that stores user reported Dash metrics in mongoDB
  metric:
    image: andreasmalling/ft_metric
    build: ./metric_server
    restart: always #due to failure if mongo boot is slow
    depends_on:
        - mongo
  
  # collects network data from user containers
  network:
    image: andreasmalling/ft_network
    build: ./network_logger
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - mongo
  
  # mongoDB microservice
  mongo:
    image: mongo:3.6.3
    volumes:
      - ./data/db:/data/db
      - ./data/dump:/data/dump
    command: --smallfiles --noprealloc
  