version: '3.5'

# basic user setup, used for extending users easily
# source: https://medium.com/@kinghuang/a1e4105d70bd
x-user: &user-template
  image: andreasmalling/ft_user
  build: ./user
  volumes:
    - ./video_dashed/:/usr/src/app/video_dashed/
  depends_on:
    - bootstrap
    - metric
    - network
    - host

services:
  # EXP NETWORK:
  # user for debugging, with sound and display pass-through
  user_debug:
    <<: *user-template
    privileged: true                    # for sound
    environment:
      - DISPLAY=${DISPLAY:- :0}         # for display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix   # for display
      - /dev/snd:/dev/snd               # for sound
    command: ${USER_DEBUG:- -r 0 --head BINGE}

  # user adding content from /videos_dashed to IPFS network
  user_seed:
    <<: *user-template
    command: ${USER_SEED:- -r 0 SEEDER}
  
  # 3 users for persona client setup (expand as seen fit)
  user_1:
    <<: *user-template
    command: ${USER_1:- IDLE}

  user_2:
    <<: *user-template
    command: ${USER_2:- IDLE}

  user_3:
    <<: *user-template
    command: ${USER_3:- IDLE}

  # MAIN NETWORK: 
  # node used for bootstraping local IPFS network
  bootstrap:
    image: andreasmalling/ft_bootstrap

  # python server hosting the website for the web player
  host:
    image: andreasmalling/ft_host
    build: ./website
    volumes:
      - ./website:/usr/src/app/

  # client that stores user reported DASH metrics in a mongoDB
  metric:
    image: andreasmalling/ft_metric
    build: ./metric_server
    restart: always     # due to failure if mongo boot is slow
    depends_on:
        - mongo
  
  # collects network data from user containers
  network:
    image: andreasmalling/ft_network
    build: ./network_logger
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - mongo
  
  # mongoDB microservice
  mongo:
    image: mongo:3.6.3
    volumes:
      - ./data/db:/data/db
      - ./data/dump:/data/dump
    command: --smallfiles --noprealloc
  